-- ============================================================================
-- PULS - Modul IDEJE (MVP 1)
-- Oracle DDL skripta - tabele, ograničenja, indeksi i podrazumevana konfiguracija
--
-- SHEMA: PORTAL (tablespace GOMEX)
--
-- !!! VAZNO !!!
-- Ova skripta se NE izvrsava automatski iz aplikacije.
-- Pregledati je i pokrenuti RUCNO nad Oracle bazom (SQL*Plus / SQL Developer).
--
-- Konvencije preuzete iz postojece PULS seme:
--   * ID kolone:        NUMBER(19,0), GENERATED BY DEFAULT AS IDENTITY
--                       (postojece PULS_* tabele koriste NUMBER(19,0) IDENTITY;
--                        BY DEFAULT je izabrano da bi SQLAlchemy INS ... RETURNING
--                        radio i da bi eventualni rucni seed sa eksplicitnim ID bio moguc)
--   * boolean kolone:   CHAR(1) sa vrednostima 'D'/'N' (Da/Ne)
--   * timestamps:       TIMESTAMP(6), default SYSTIMESTAMP
--   * svaka tabela:     DATUM_KREIRANJA, a mutabilne i DATUM_IZMENE
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1) PULS_IDEA_CIKLUSI - ciklusi (kampanje) za prikupljanje ideja
-- ----------------------------------------------------------------------------
-- NAPOMENA (charset): baza koristi NLS_CHARACTERSET=EE8ISO8859P2, koji NE cuva
-- cirilicu/emoji (tiho ih pretvara u '?'). Zato korisnicki tekst (NAZIV, NASLOV,
-- OPIS) ide u N-tipove (NVARCHAR2/NCLOB, NLS_NCHAR_CHARACTERSET=AL16UTF16).
-- Kontrolisani kodovi i postojeci podaci (PLATNI_BROJ, IME/PREZIME_AUTORA,
-- ORGJED_SIFRA, STATUS) ostaju VARCHAR2.
CREATE TABLE PULS_IDEA_CIKLUSI (
    ID                NUMBER(19,0)   GENERATED BY DEFAULT AS IDENTITY,
    NAZIV             NVARCHAR2(200) NOT NULL,
    DATUM_POCETKA     TIMESTAMP(6)   NOT NULL,
    DATUM_ZAVRSETKA   TIMESTAMP(6)   NOT NULL,
    STATUS            VARCHAR2(20)   DEFAULT 'PLANIRAN' NOT NULL,
    DATUM_KREIRANJA   TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    DATUM_IZMENE      TIMESTAMP(6),
    CONSTRAINT PK_PULS_IDEA_CIKLUSI PRIMARY KEY (ID),
    CONSTRAINT CK_IDEA_CIKLUS_STATUS
        CHECK (STATUS IN ('PLANIRAN', 'AKTIVAN', 'ZATVOREN')),
    CONSTRAINT CK_IDEA_CIKLUS_DATUMI
        CHECK (DATUM_ZAVRSETKA > DATUM_POCETKA)
);

-- Najvise jedan AKTIVAN ciklus u datom trenutku.
-- Function-based unikatni indeks: samo redovi sa STATUS='AKTIVAN' ulaze u indeks
-- (ostali dobijaju NULL i ne konfliktuju).
CREATE UNIQUE INDEX UX_IDEA_CIKLUS_JEDAN_AKTIVAN
    ON PULS_IDEA_CIKLUSI (CASE WHEN STATUS = 'AKTIVAN' THEN 1 ELSE NULL END);

CREATE INDEX IX_IDEA_CIKLUS_STATUS ON PULS_IDEA_CIKLUSI (STATUS);


-- ----------------------------------------------------------------------------
-- 2) PULS_IDEJE - pojedinacne ideje zaposlenih
--
-- Autorovi podaci (PLATNI_BROJ, IME_AUTORA, PREZIME_AUTORA, ORGJED_SIFRA) su
-- SNAPSHOT u trenutku slanja ideje - istorija ostaje sacuvana i kada se ime ili
-- organizaciona jedinica kasnije promene.
-- ----------------------------------------------------------------------------
CREATE TABLE PULS_IDEJE (
    ID                NUMBER(19,0)   GENERATED BY DEFAULT AS IDENTITY,
    KORISNIK_ID       NUMBER(19,0)   NOT NULL,
    CIKLUS_ID         NUMBER(19,0)   NOT NULL,
    PLATNI_BROJ       VARCHAR2(30)   NOT NULL,
    IME_AUTORA        VARCHAR2(100)  NOT NULL,
    PREZIME_AUTORA    VARCHAR2(100)  NOT NULL,
    ORGJED_SIFRA      VARCHAR2(50),
    NASLOV            NVARCHAR2(200) NOT NULL,
    OPIS              NCLOB          NOT NULL,
    STATUS            VARCHAR2(20)   DEFAULT 'POSLATA' NOT NULL,
    HR_OCENA          NUMBER(2,0),
    AI_OCENA          NUMBER(4,2),
    KONACNA_OCENA     NUMBER(5,2),
    DATUM_KREIRANJA   TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    DATUM_IZMENE      TIMESTAMP(6),
    CONSTRAINT PK_PULS_IDEJE PRIMARY KEY (ID),
    CONSTRAINT FK_IDEJE_KORISNIK
        FOREIGN KEY (KORISNIK_ID) REFERENCES PULS_KORISNICI (ID),
    CONSTRAINT FK_IDEJE_CIKLUS
        FOREIGN KEY (CIKLUS_ID) REFERENCES PULS_IDEA_CIKLUSI (ID),
    CONSTRAINT CK_IDEJE_STATUS
        CHECK (STATUS IN ('POSLATA', 'U_OBRADI', 'ODOBRENA', 'ODBIJENA', 'TOP_10', 'NAGRAĐENA')),
    CONSTRAINT CK_IDEJE_HR_OCENA
        CHECK (HR_OCENA IS NULL OR (HR_OCENA BETWEEN 1 AND 10)),
    CONSTRAINT CK_IDEJE_AI_OCENA
        CHECK (AI_OCENA IS NULL OR (AI_OCENA BETWEEN 1 AND 10))
);

CREATE INDEX IX_IDEJE_KORISNIK   ON PULS_IDEJE (KORISNIK_ID);
CREATE INDEX IX_IDEJE_CIKLUS     ON PULS_IDEJE (CIKLUS_ID);
CREATE INDEX IX_IDEJE_STATUS     ON PULS_IDEJE (STATUS);
-- Brojanje poslatih ideja po korisniku unutar ciklusa (limit provera).
CREATE INDEX IX_IDEJE_KORISNIK_CIKLUS ON PULS_IDEJE (CIKLUS_ID, KORISNIK_ID);
-- Rangiranje najboljih ideja (KONACNA_OCENA DESC, HR_OCENA DESC, ...).
CREATE INDEX IX_IDEJE_RANG ON PULS_IDEJE (CIKLUS_ID, STATUS, KONACNA_OCENA, HR_OCENA);


-- ----------------------------------------------------------------------------
-- 3) KONFIGURACIJA (podrazumevane vrednosti)
--
-- Modul koristi POSTOJECU tabelu PULS_KONFIGURACIJA (ne pravi novu).
-- Ovaj MERGE dodaje kljuceve samo ako ne postoje. Aplikacija ionako ima fallback
-- vrednosti (MAX_IDEJA_PO_CIKLUSU=3, TOP_IDEAS_COUNT=10), pa je ovaj blok
-- opcionalan. Pokrenuti RUCNO ako zelite da vrednosti budu vidljive/podesive u bazi.
-- ----------------------------------------------------------------------------
MERGE INTO PULS_KONFIGURACIJA k
USING (SELECT 'MAX_IDEJA_PO_CIKLUSU' AS KLJUC FROM DUAL) src
   ON (k.KLJUC = src.KLJUC)
WHEN NOT MATCHED THEN
    INSERT (KLJUC, VREDNOST, TIP_PODATKA, OPIS, AKTIVNA)
    VALUES ('MAX_IDEJA_PO_CIKLUSU', '3', 'BROJ',
            'Maksimalan broj ideja koje jedan korisnik moze poslati po ciklusu.', 'D');

MERGE INTO PULS_KONFIGURACIJA k
USING (SELECT 'TOP_IDEAS_COUNT' AS KLJUC FROM DUAL) src
   ON (k.KLJUC = src.KLJUC)
WHEN NOT MATCHED THEN
    INSERT (KLJUC, VREDNOST, TIP_PODATKA, OPIS, AKTIVNA)
    VALUES ('TOP_IDEAS_COUNT', '10', 'BROJ',
            'Broj ideja koje se prikazuju na listi najboljih ideja.', 'D');

COMMIT;
