-- ============================================================================
-- PULS - Modul OBAVESTENJA (Faza 1)
-- Oracle DDL: tabele, ogranicenja, indeksi i podrazumevana konfiguracija
--
-- SHEMA: PORTAL           TABLESPACE: GOMEX           ORACLE: 19c
--
-- !!! VAZNO !!!
-- Ova skripta se NE izvrsava automatski iz aplikacije. Mora se RUCNO pregledati
-- i pokrenuti (SQL Developer / SQL*Plus) tek nakon nezavisnog pregleda.
--
-- Charset (potvrdjeno u prethodnim modulima):
--   NLS_CHARACTERSET       = EE8ISO8859P2  (NE cuva cirilicu/emoji u VARCHAR2!)
--   NLS_NCHAR_CHARACTERSET = AL16UTF16
-- Zato korisnicki tekst (NAZIV/NASLOV/KRATAK_TEKST/SADRZAJ) ide u NVARCHAR2/NCLOB,
-- a kontrolisani kodovi/statusi/platni broj/orgjed sifre/URL ostaju VARCHAR2.
--
-- Konvencije (kao ostale PULS tabele):
--   ID       NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY
--   boolean  CHAR(1) 'D'/'N'
--   vreme    TIMESTAMP(6), DATUM_KREIRANJA DEFAULT SYSTIMESTAMP
--
-- Skripta NE sadrzi: DROP / DELETE / TRUNCATE / destruktivni ALTER / izmene
-- postojecih tabela. Pocetne kategorije se dodaju bezbednim MERGE obrascem
-- (bez prepisivanja postojecih vrednosti) - to su sistemske konfiguracione
-- vrednosti, a NE testni podaci.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1) PULS_OBAVESTENJE_KATEGORIJE - konfiguracione kategorije obavestenja
-- ----------------------------------------------------------------------------
CREATE TABLE PULS_OBAVESTENJE_KATEGORIJE (
    SIFRA             VARCHAR2(50)   NOT NULL,
    NAZIV             NVARCHAR2(100) NOT NULL,
    AKTIVNA           CHAR(1)        DEFAULT 'D' NOT NULL,
    REDOSLED          NUMBER(10,0),
    DATUM_KREIRANJA   TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    DATUM_IZMENE      TIMESTAMP(6),
    CONSTRAINT PK_PULS_OBAV_KATEGORIJE PRIMARY KEY (SIFRA),
    CONSTRAINT CK_OBAV_KAT_AKTIVNA CHECK (AKTIVNA IN ('D', 'N'))
);


-- ----------------------------------------------------------------------------
-- 2) PULS_OBAVESTENJA - jedno obavestenje (DRAFT -> PUBLISHED -> ARCHIVED)
--
-- RESURS_ID namerno NEMA FK ka Ideji/Anketi: znacenje zavisi od AKCIJA_TIP
-- (SURVEY -> anketa, IDEA -> ideja), pa se integritet cuva u servisnom sloju.
-- ----------------------------------------------------------------------------
CREATE TABLE PULS_OBAVESTENJA (
    ID                    NUMBER(19,0)   GENERATED BY DEFAULT AS IDENTITY,
    KATEGORIJA_SIFRA      VARCHAR2(50)   NOT NULL,
    NASLOV                NVARCHAR2(200) NOT NULL,
    KRATAK_TEKST          NVARCHAR2(500) NOT NULL,
    SADRZAJ               NCLOB          NOT NULL,
    STATUS                VARCHAR2(20)   DEFAULT 'DRAFT' NOT NULL,
    AKCIJA_TIP            VARCHAR2(30)   DEFAULT 'NONE' NOT NULL,
    RESURS_ID             NUMBER(19,0),
    AKCIJA_URL            VARCHAR2(1000),
    KREIRAO_PLATNI_BROJ   VARCHAR2(30),
    DATUM_OBJAVE          TIMESTAMP(6),
    DATUM_ISTEKA          TIMESTAMP(6),
    DATUM_KREIRANJA       TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    DATUM_IZMENE          TIMESTAMP(6),
    CONSTRAINT PK_PULS_OBAVESTENJA PRIMARY KEY (ID),
    CONSTRAINT FK_OBAV_KATEGORIJA
        FOREIGN KEY (KATEGORIJA_SIFRA) REFERENCES PULS_OBAVESTENJE_KATEGORIJE (SIFRA),
    CONSTRAINT CK_OBAV_STATUS
        CHECK (STATUS IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT CK_OBAV_AKCIJA_TIP
        CHECK (AKCIJA_TIP IN ('NONE', 'SURVEY', 'IDEA', 'URL')),
    -- Datum isteka mora biti posle datuma objave kada su OBA postavljena.
    CONSTRAINT CK_OBAV_DATUMI
        CHECK (DATUM_OBJAVE IS NULL OR DATUM_ISTEKA IS NULL OR DATUM_ISTEKA > DATUM_OBJAVE),
    -- PUBLISHED mora imati i datum objave i datum isteka.
    CONSTRAINT CK_OBAV_PUBLISHED_DATUMI
        CHECK (STATUS <> 'PUBLISHED' OR (DATUM_OBJAVE IS NOT NULL AND DATUM_ISTEKA IS NOT NULL)),
    -- Pravila akcije: NONE bez resursa/URL; SURVEY/IDEA sa RESURS_ID i bez URL;
    -- URL sa URL i bez RESURS_ID.
    CONSTRAINT CK_OBAV_AKCIJA_PODACI CHECK (
        (AKCIJA_TIP = 'NONE' AND RESURS_ID IS NULL AND AKCIJA_URL IS NULL) OR
        (AKCIJA_TIP IN ('SURVEY', 'IDEA') AND RESURS_ID IS NOT NULL AND AKCIJA_URL IS NULL) OR
        (AKCIJA_TIP = 'URL' AND AKCIJA_URL IS NOT NULL AND RESURS_ID IS NULL)),
    -- RESURS_ID (kada postoji) mora biti pozitivan. NAPOMENA: postojanje konkretne
    -- ankete/ideje se NE proverava u bazi (znacenje zavisi od AKCIJA_TIP) - to je
    -- ugovor admin/automatske integracije u servisnom sloju.
    CONSTRAINT CK_OBAV_RESURS_POZITIVAN CHECK (RESURS_ID IS NULL OR RESURS_ID > 0)
);
-- Inbox/admin filtriranje i sortiranje.
CREATE INDEX IX_OBAV_STATUS     ON PULS_OBAVESTENJA (STATUS);
CREATE INDEX IX_OBAV_KATEGORIJA ON PULS_OBAVESTENJA (KATEGORIJA_SIFRA);
-- Sortiranje/filtriranje objavljenih po datumu objave (DESC se resava u upitu).
CREATE INDEX IX_OBAV_OBJAVA     ON PULS_OBAVESTENJA (STATUS, DATUM_OBJAVE, DATUM_ISTEKA);


-- ----------------------------------------------------------------------------
-- 3) PULS_OBAVESTENJE_CILJEVI - ciljne grupe obavestenja
--
-- CENTRALA/MALOPRODAJA postoje u modelu, ali ih publishing servis trenutno
-- odbija (nema pouzdanog HR mapiranja). Ne nagadja se mapiranje.
-- ----------------------------------------------------------------------------
CREATE TABLE PULS_OBAVESTENJE_CILJEVI (
    ID                NUMBER(19,0)   GENERATED BY DEFAULT AS IDENTITY,
    OBAVESTENJE_ID    NUMBER(19,0)   NOT NULL,
    TIP_CILJA         VARCHAR2(20)   NOT NULL,
    VREDNOST          VARCHAR2(100),
    DATUM_KREIRANJA   TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PULS_OBAV_CILJEVI PRIMARY KEY (ID),
    CONSTRAINT FK_OBAV_CILJ_OBAV
        FOREIGN KEY (OBAVESTENJE_ID) REFERENCES PULS_OBAVESTENJA (ID),
    CONSTRAINT CK_OBAV_CILJ_TIP
        CHECK (TIP_CILJA IN ('SVI', 'CENTRALA', 'MALOPRODAJA', 'ORGJED', 'PLATNI_BROJ')),
    -- SVI/CENTRALA/MALOPRODAJA nemaju vrednost; ORGJED/PLATNI_BROJ je zahtevaju.
    CONSTRAINT CK_OBAV_CILJ_VREDNOST CHECK (
        (TIP_CILJA IN ('SVI', 'CENTRALA', 'MALOPRODAJA') AND VREDNOST IS NULL) OR
        (TIP_CILJA IN ('ORGJED', 'PLATNI_BROJ') AND VREDNOST IS NOT NULL))
);
-- Spreci duple ciljeve za isto obavestenje. NVL(VREDNOST,'*') je nuzan jer Oracle
-- UNIQUE nad NULL kolonom NE bi sprecio dva reda ('SVI', NULL) za isto obavestenje.
CREATE UNIQUE INDEX UX_OBAV_CILJ_JEDINSTVEN
    ON PULS_OBAVESTENJE_CILJEVI (OBAVESTENJE_ID, TIP_CILJA, NVL(VREDNOST, '*'));
CREATE INDEX IX_OBAV_CILJ_OBAV ON PULS_OBAVESTENJE_CILJEVI (OBAVESTENJE_ID);


-- ----------------------------------------------------------------------------
-- 4) PULS_OBAVESTENJE_PRIMAOCI - materijalizovana lista primalaca u trenutku
--    objavljivanja. Vidljivost kasnije NE zavisi od promene org. jedinice.
-- ----------------------------------------------------------------------------
CREATE TABLE PULS_OBAVESTENJE_PRIMAOCI (
    ID                NUMBER(19,0)   GENERATED BY DEFAULT AS IDENTITY,
    OBAVESTENJE_ID    NUMBER(19,0)   NOT NULL,
    KORISNIK_ID       NUMBER(19,0)   NOT NULL,
    PROCITANO         CHAR(1)        DEFAULT 'N' NOT NULL,
    DATUM_CITANJA     TIMESTAMP(6),
    DATUM_KREIRANJA   TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    DATUM_IZMENE      TIMESTAMP(6),
    CONSTRAINT PK_PULS_OBAV_PRIMAOCI PRIMARY KEY (ID),
    CONSTRAINT FK_OBAV_PRIM_OBAV
        FOREIGN KEY (OBAVESTENJE_ID) REFERENCES PULS_OBAVESTENJA (ID),
    CONSTRAINT FK_OBAV_PRIM_KORISNIK
        FOREIGN KEY (KORISNIK_ID) REFERENCES PULS_KORISNICI (ID),
    CONSTRAINT CK_OBAV_PRIM_PROCITANO CHECK (PROCITANO IN ('D', 'N')),
    -- PROCITANO='N' -> DATUM_CITANJA NULL; PROCITANO='D' -> DATUM_CITANJA popunjen.
    CONSTRAINT CK_OBAV_PRIM_CITANJE CHECK (
        (PROCITANO = 'N' AND DATUM_CITANJA IS NULL) OR
        (PROCITANO = 'D' AND DATUM_CITANJA IS NOT NULL)),
    CONSTRAINT UX_OBAV_PRIM_JEDINSTVEN UNIQUE (OBAVESTENJE_ID, KORISNIK_ID)
);
-- Lista obavestenja jednog korisnika + broj neprocitanih (KORISNIK_ID, PROCITANO).
CREATE INDEX IX_OBAV_PRIM_KORISNIK ON PULS_OBAVESTENJE_PRIMAOCI (KORISNIK_ID, PROCITANO);
-- Nalazenje svih primalaca jednog obavestenja.
CREATE INDEX IX_OBAV_PRIM_OBAV     ON PULS_OBAVESTENJE_PRIMAOCI (OBAVESTENJE_ID);


-- ----------------------------------------------------------------------------
-- 5) POCETNE KATEGORIJE (sistemske konfiguracione vrednosti, NE testni podaci)
--    Bezbedan MERGE: dodaje samo ako SIFRA jos ne postoji (ne prepisuje NAZIV/
--    AKTIVNA/REDOSLED za postojece redove).
-- ----------------------------------------------------------------------------
MERGE INTO PULS_OBAVESTENJE_KATEGORIJE k
USING (SELECT 'ANKETA' AS SIFRA FROM DUAL) src ON (k.SIFRA = src.SIFRA)
WHEN NOT MATCHED THEN INSERT (SIFRA, NAZIV, AKTIVNA, REDOSLED)
     VALUES ('ANKETA', 'Ankete', 'D', 10);

MERGE INTO PULS_OBAVESTENJE_KATEGORIJE k
USING (SELECT 'IDEJA' AS SIFRA FROM DUAL) src ON (k.SIFRA = src.SIFRA)
WHEN NOT MATCHED THEN INSERT (SIFRA, NAZIV, AKTIVNA, REDOSLED)
     VALUES ('IDEJA', 'Ideje', 'D', 20);

MERGE INTO PULS_OBAVESTENJE_KATEGORIJE k
USING (SELECT 'HR' AS SIFRA FROM DUAL) src ON (k.SIFRA = src.SIFRA)
WHEN NOT MATCHED THEN INSERT (SIFRA, NAZIV, AKTIVNA, REDOSLED)
     VALUES ('HR', 'HR', 'D', 30);

MERGE INTO PULS_OBAVESTENJE_KATEGORIJE k
USING (SELECT 'OPSTE' AS SIFRA FROM DUAL) src ON (k.SIFRA = src.SIFRA)
WHEN NOT MATCHED THEN INSERT (SIFRA, NAZIV, AKTIVNA, REDOSLED)
     VALUES ('OPSTE', 'Opšte', 'D', 40);

MERGE INTO PULS_OBAVESTENJE_KATEGORIJE k
USING (SELECT 'SISTEM' AS SIFRA FROM DUAL) src ON (k.SIFRA = src.SIFRA)
WHEN NOT MATCHED THEN INSERT (SIFRA, NAZIV, AKTIVNA, REDOSLED)
     VALUES ('SISTEM', 'Sistemsko', 'D', 50);


-- ----------------------------------------------------------------------------
-- 6) KONFIGURACIJA - podrazumevani rok isteka obavestenja (dana)
--    Koristi POSTOJECU tabelu PULS_KONFIGURACIJA; dodaje kljuc samo ako ne postoji.
--    Aplikacija ima fallback (30), pa je blok opcionalan.
-- ----------------------------------------------------------------------------
MERGE INTO PULS_KONFIGURACIJA k
USING (SELECT 'NOTIFICATION_DEFAULT_EXPIRY_DAYS' AS KLJUC FROM DUAL) src
   ON (k.KLJUC = src.KLJUC)
WHEN NOT MATCHED THEN
    INSERT (KLJUC, VREDNOST, TIP_PODATKA, OPIS, AKTIVNA)
    VALUES ('NOTIFICATION_DEFAULT_EXPIRY_DAYS', '30', 'BROJ',
            'Podrazumevani broj dana do isteka obavestenja pri objavljivanju.', 'D');

COMMIT;
