-- ============================================================================
-- PULS - Modul FCM PUSH (Firebase Cloud Messaging) - dopuna modula OBAVESTENJA
-- Oracle DDL: tabele, ogranicenja, indeksi
--
-- SHEMA: PORTAL           TABLESPACE: GOMEX           ORACLE: 19c
--
-- !!! VAZNO !!!
-- Ova skripta se NE izvrsava automatski i NIJE idempotentna migracija.
-- Izvrsava se RUCNO, TACNO JEDNOM, tek nakon read-only pre-flight provere
-- (kao sql/003). Ne sadrzi DROP/DELETE/TRUNCATE/ALTER ni testne podatke.
--
-- Push je DODATNI kanal; Oracle Inbox (PULS_OBAVESTENJA/PRIMAOCI) ostaje jedini
-- izvor istine. Ako FCM nije dostupan, obavestenje je i dalje vidljivo u Inbox-u.
--
-- BEZBEDNOST:
--   * FCM_TOKEN je tajna vrednost - NIKADA se ne loguje niti prikazuje u celosti.
--     Za pretragu/jedinstvenost koristi se SHA-256 TOKEN_HASH, a NE indeks nad
--     punim FCM_TOKEN poljem.
--   * POSLEDNJI_ERROR_CODE cuva samo bezbedan FCM kod greske - bez tokena/tajni.
--
-- SEMANTIKA STATUSA (PULS_PUSH_ISPORUKE.STATUS):
--   PENDING  - ceka slanje (worker ce ga preuzeti)
--   SENT     - FCM je PRIHVATIO poruku. NIJE potvrda dostave uredjaju!
--   FAILED   - trajno neuspesno nakon maksimalnog broja pokusaja
--   SKIPPED  - preskoceno (obavestenje isteklo/arhivirano, korisnik neaktivan,
--              nema aktivan token ili vise nema pravo na obavestenje)
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1) PULS_PUSH_TOKENI - registrovani FCM tokeni po korisniku i uredjaju
--
-- Pravilo "jedan aktivan uredjaj": u datom trenutku korisnik ima najvise jedan
-- AKTIVAN token (deaktivacija starih se radi u servisnom sloju pri login/logout/
-- reset, PRE aktivacije/kreiranja novog reda - vidi PushTokenRepository.upsert).
-- Puni FCM_TOKEN NIJE indeksiran; jedinstvenost ide preko TOKEN_HASH.
--
-- NAPOMENA (istorijski tokeni): TOKEN_HASH namerno NIJE globalno UNIQUE preko
-- CONSTRAINT-a, jer isti fizicki FCM token prirodno prolazi kroz vise redova
-- tokom vremena (stari korisnik deaktivira token pri logout-u/novom login-u,
-- pa se isti fizicki token kasnije registruje kod drugog korisnika ili drugog
-- naloga na istom uredjaju). Deaktivirani (AKTIVAN='N') istorijski redovi zato
-- SMEJU deliti isti TOKEN_HASH. Jedinstvenost se umesto toga garantuje SAMO
-- MEDJU AKTIVNIM redovima preko function-based unique indeksa ispod.
-- ----------------------------------------------------------------------------
CREATE TABLE PULS_PUSH_TOKENI (
    ID                            NUMBER(19,0)   GENERATED BY DEFAULT AS IDENTITY,
    KORISNIK_ID                   NUMBER(19,0)   NOT NULL,
    UREDJAJ_ID                    VARCHAR2(255)  NOT NULL,
    FCM_TOKEN                     VARCHAR2(4000) NOT NULL,
    TOKEN_HASH                    VARCHAR2(64)   NOT NULL,
    AKTIVAN                       CHAR(1)        DEFAULT 'D' NOT NULL,
    APP_VERSION                   VARCHAR2(50),
    DATUM_KREIRANJA               TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    DATUM_IZMENE                  TIMESTAMP(6),
    DATUM_POSLEDNJE_REGISTRACIJE  TIMESTAMP(6),
    DATUM_DEAKTIVACIJE            TIMESTAMP(6),
    CONSTRAINT PK_PULS_PUSH_TOKENI PRIMARY KEY (ID),
    CONSTRAINT FK_PUSH_TOKEN_KORISNIK
        FOREIGN KEY (KORISNIK_ID) REFERENCES PULS_KORISNICI (ID),
    CONSTRAINT CK_PUSH_TOKEN_AKTIVAN CHECK (AKTIVAN IN ('D', 'N')),
    -- Jedan red po (korisnik, uredjaj) - upsert reaktivira/azurira postojeci red.
    CONSTRAINT UX_PUSH_TOKEN_KOR_UREDJAJ UNIQUE (KORISNIK_ID, UREDJAJ_ID)
);
-- Brzo nalazenje aktivnog tokena korisnika.
CREATE INDEX IX_PUSH_TOKEN_KORISNIK ON PULS_PUSH_TOKENI (KORISNIK_ID, AKTIVAN);

-- Isti fizicki FCM token sme postojati u vise (istorijskih/neaktivnih) redova,
-- ali SAMO JEDNOM medju trenutno aktivnim (AKTIVAN='D') redovima. CASE->NULL
-- za neaktivne redove ih iskljucuje iz indeksa (Oracle unique indeks ignorise
-- NULL), pa oni mogu slobodno deliti isti TOKEN_HASH.
CREATE UNIQUE INDEX UX_PUSH_TOKEN_AKTIVAN_HASH
    ON PULS_PUSH_TOKENI (CASE WHEN AKTIVAN = 'D' THEN TOKEN_HASH END);

-- DB zastita pravila "jedan aktivan uredjaj": korisnik sme imati najvise jedan
-- AKTIVAN red (bez obzira na uredjaj). Isti CASE->NULL trik za neaktivne redove.
CREATE UNIQUE INDEX UX_PUSH_TOKEN_AKTIVAN_KOR
    ON PULS_PUSH_TOKENI (CASE WHEN AKTIVAN = 'D' THEN KORISNIK_ID END);


-- ----------------------------------------------------------------------------
-- 2) PULS_PUSH_ISPORUKE - outbox red po primaocu (jedan po obavestenju/korisniku)
--
-- Pri prvom publish-u obavestenja nastaje po jedan PENDING red za svakog primaoca
-- (u ISTOJ transakciji kao materijalizacija PULS_OBAVESTENJE_PRIMAOCI). Zaseban
-- push worker kasnije preuzima PENDING redove. Ponovljeno slanje NE pravi duple
-- redove: postojeci red se bezbedno vraca u PENDING i BROJ_PONOVNIH_SLANJA += 1.
-- ----------------------------------------------------------------------------
CREATE TABLE PULS_PUSH_ISPORUKE (
    ID                        NUMBER(19,0)  GENERATED BY DEFAULT AS IDENTITY,
    OBAVESTENJE_ID            NUMBER(19,0)  NOT NULL,
    KORISNIK_ID               NUMBER(19,0)  NOT NULL,
    STATUS                    VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    BROJ_POKUSAJA             NUMBER(10,0)  DEFAULT 0 NOT NULL,
    DATUM_SLEDECEG_POKUSAJA   TIMESTAMP(6),
    POSLEDNJI_ERROR_CODE      VARCHAR2(100),
    DATUM_KREIRANJA           TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    DATUM_POSLEDNJEG_POKUSAJA TIMESTAMP(6),
    DATUM_SLANJA              TIMESTAMP(6),
    BROJ_PONOVNIH_SLANJA      NUMBER(10,0)  DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PULS_PUSH_ISPORUKE PRIMARY KEY (ID),
    CONSTRAINT FK_PUSH_ISP_OBAV
        FOREIGN KEY (OBAVESTENJE_ID) REFERENCES PULS_OBAVESTENJA (ID),
    CONSTRAINT FK_PUSH_ISP_KORISNIK
        FOREIGN KEY (KORISNIK_ID) REFERENCES PULS_KORISNICI (ID),
    CONSTRAINT CK_PUSH_ISP_STATUS
        CHECK (STATUS IN ('PENDING', 'SENT', 'FAILED', 'SKIPPED')),
    CONSTRAINT CK_PUSH_ISP_POKUSAJA CHECK (BROJ_POKUSAJA >= 0),
    CONSTRAINT CK_PUSH_ISP_PONOVNIH CHECK (BROJ_PONOVNIH_SLANJA >= 0),
    -- Jedan inicijalni push red po primaocu (idempotentnost publish/resend).
    CONSTRAINT UX_PUSH_ISP_OBAV_KOR UNIQUE (OBAVESTENJE_ID, KORISNIK_ID)
);
-- Worker batch: preuzimanje spremnih PENDING redova po vremenu sledeceg pokusaja.
CREATE INDEX IX_PUSH_ISP_READY    ON PULS_PUSH_ISPORUKE (STATUS, DATUM_SLEDECEG_POKUSAJA);
CREATE INDEX IX_PUSH_ISP_KORISNIK ON PULS_PUSH_ISPORUKE (KORISNIK_ID);
CREATE INDEX IX_PUSH_ISP_OBAV     ON PULS_PUSH_ISPORUKE (OBAVESTENJE_ID);

COMMIT;
