-- ============================================================================
-- PULS - Modul SISTEMSKA OBAVESTENJA - dopuna modula OBAVESTENJA/FCM PUSH
-- Oracle DDL: nova tabela + kontrolisan ALTER postojecih CHECK ogranicenja
--
-- SHEMA: PORTAL           TABLESPACE: GOMEX           ORACLE: 19c
--
-- !!! VAZNO !!!
-- Ova skripta se NE izvrsava automatski iz aplikacije. Mora se RUCNO pregledati
-- i pokrenuti (SQL Developer / SQL*Plus) tek nakon nezavisnog pregleda, POSLE
-- sql/003_notifications_module.sql i sql/004_fcm_push_module.sql.
--
-- Skripta NE sadrzi DROP / DELETE / TRUNCATE / testne podatke. Jedini ALTER je
-- kontrolisano prosirenje dva postojeca CHECK ogranicenja (obrazlozeno ispod).
--
-- Charset (isto pravilo kao ostali moduli):
--   NLS_CHARACTERSET       = EE8ISO8859P2  (NE cuva cirilicu/emoji u VARCHAR2!)
--   NLS_NCHAR_CHARACTERSET = AL16UTF16
-- PULS_SISTEMSKI_DOGADJAJI ne cuva korisnicki tekst (samo kontrolisane kodove/ID-jeve/
-- verziju) - zato su sve kolone VARCHAR2, bez NVARCHAR2/NCLOB.
--
-- ARHITEKTURA (kontekst za pregledaca):
--   Oracle Inbox (PULS_OBAVESTENJA/PRIMAOCI) ostaje jedini izvor istine. FCM je
--   dodatni kanal preko VEC POSTOJECEG PULS_PUSH_ISPORUKE (bez novih push tabela).
--   PULS_SISTEMSKI_DOGADJAJI je iskljucivo idempotentni RADNI RED za zaseban
--   "system_notification_worker" proces (jedna instanca, bez Redis/Celery) - ne
--   dodaje se scheduler u web procesu.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1) PULS_SISTEMSKI_DOGADJAJI - idempotentni event queue za automatska SISTEM
--    obavestenja (aktivacija/istek ankete, aktivacija/istek ciklusa ideja,
--    TOP_10/NAGRADJENA, promena CURRENT_VERSION).
--
-- DOGADJAJ_KLJUC je JEDINI mehanizam idempotentnosti - jedinstven preko cele
-- tabele (UNIQUE), pa dupli enqueue poziv (npr. konkurentan admin retry) nikada
-- ne pravi dva reda za isti logicki dogadjaj:
--   * aktivacija/status/verzija: 'TIP:RESURS_ID'            (npr. 'SURVEY_ACTIVATED:123')
--   * podsetnik (rok):           'TIP:RESURS_ID:DATUM_ISO'  (npr. 'SURVEY_EXPIRING:123:2026-03-01T10:00:00')
--     - produzenje roka MENJA kljuc (nov DATUM_ISO), pa NAMERNO dozvoljava nov
--       podsetnik za produzeni rok bez posebne logike brisanja starog.
--
-- RESURS_ID namerno NEMA FK (znacenje zavisi od TIP_DOGADJAJA - anketa/ciklus/
-- ideja), isti obrazac kao PULS_OBAVESTENJA.RESURS_ID. OBAVESTENJE_ID FK se
-- postavlja tek KADA worker uspesno materijalizuje Inbox obavestenje (PROCESSED).
-- ----------------------------------------------------------------------------
CREATE TABLE PULS_SISTEMSKI_DOGADJAJI (
    ID                        NUMBER(19,0)  GENERATED BY DEFAULT AS IDENTITY,
    DOGADJAJ_KLJUC            VARCHAR2(300) NOT NULL,
    TIP_DOGADJAJA             VARCHAR2(30)  NOT NULL,
    RESURS_ID                 NUMBER(19,0),
    -- Verzija (APP_VERSION_CHANGED) ili drugi bezbedan marker - NIKADA tajna/token.
    VREDNOST                  VARCHAR2(100),
    STATUS                    VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    BROJ_POKUSAJA             NUMBER(10,0)  DEFAULT 0 NOT NULL,
    DATUM_SLEDECEG_POKUSAJA   TIMESTAMP(6),
    -- Samo bezbedan kod greske (npr. naziv exception klase) - NIKADA puna poruka/tajne.
    POSLEDNJI_ERROR_CODE      VARCHAR2(100),
    OBAVESTENJE_ID            NUMBER(19,0),
    DATUM_KREIRANJA           TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    DATUM_OBRADE              TIMESTAMP(6),
    CONSTRAINT PK_PULS_SIST_DOGADJAJI PRIMARY KEY (ID),
    CONSTRAINT UX_SIST_DOG_KLJUC UNIQUE (DOGADJAJ_KLJUC),
    CONSTRAINT FK_SIST_DOG_OBAV
        FOREIGN KEY (OBAVESTENJE_ID) REFERENCES PULS_OBAVESTENJA (ID),
    CONSTRAINT CK_SIST_DOG_STATUS
        CHECK (STATUS IN ('PENDING', 'PROCESSED', 'SKIPPED', 'FAILED')),
    CONSTRAINT CK_SIST_DOG_TIP CHECK (TIP_DOGADJAJA IN (
        'SURVEY_ACTIVATED', 'SURVEY_EXPIRING',
        'IDEA_CYCLE_ACTIVATED', 'IDEA_CYCLE_EXPIRING',
        'IDEA_TOP_10', 'IDEA_NAGRADJENA',
        'APP_VERSION_CHANGED')),
    CONSTRAINT CK_SIST_DOG_POKUSAJA CHECK (BROJ_POKUSAJA >= 0),
    CONSTRAINT CK_SIST_DOG_RESURS_POZITIVAN CHECK (RESURS_ID IS NULL OR RESURS_ID > 0),
    -- PROCESSED mora imati OBAVESTENJE_ID; nijedan drugi status ga ne sme imati
    -- (SKIPPED/FAILED/PENDING nikada nisu materijalizovali Inbox obavestenje).
    CONSTRAINT CK_SIST_DOG_PROCESSED_OBAV CHECK (
        (STATUS = 'PROCESSED' AND OBAVESTENJE_ID IS NOT NULL) OR
        (STATUS <> 'PROCESSED' AND OBAVESTENJE_ID IS NULL))
);
-- Worker batch: PENDING redovi spremni za obradu po vremenu sledeceg pokusaja
-- (isti obrazac kao IX_PUSH_ISP_READY u sql/004).
CREATE INDEX IX_SIST_DOG_READY ON PULS_SISTEMSKI_DOGADJAJI (STATUS, DATUM_SLEDECEG_POKUSAJA);
-- Nalazenje svih dogadjaja jednog resursa (npr. dijagnostika/audit uvid).
CREATE INDEX IX_SIST_DOG_RESURS ON PULS_SISTEMSKI_DOGADJAJI (TIP_DOGADJAJA, RESURS_ID);


-- ----------------------------------------------------------------------------
-- 2) ALTER PULS_OBAVESTENJA - novi tip akcije IDEA_CYCLE (RESURS_ID = PULS_IDEA_CIKLUSI.ID)
--
-- ZASTO JE ALTER POTREBAN: CK_OBAV_AKCIJA_TIP i CK_OBAV_AKCIJA_PODACI iz
-- sql/003_notifications_module.sql eksplicitno nabrajaju dozvoljene AKCIJA_TIP
-- vrednosti ('NONE','SURVEY','IDEA','URL'). Sistemska obavestenja o aktivaciji/
-- isteku ciklusa ideja moraju nositi akciju koja Android aplikaciju vodi na
-- konkretan ciklus (RESURS_ID), a ne na anketu/ideju/URL - zato je IDEA_CYCLE nov,
-- zaseban tip. Oracle CHECK ogranicenja se ne mogu "dopuniti" bez DROP+ADD; ovo
-- je kontrolisan, ADITIVAN alter (stariji redovi i dalje zadovoljavaju novi CHECK
-- jer im AKCIJA_TIP ostaje NONE/SURVEY/IDEA/URL - skup dozvoljenih vrednosti se
-- samo PROSIRUJE, ne suzava). Nema DROP TABLE/DELETE/TRUNCATE niti gubitka podataka.
--
-- IDEA_CYCLE prati ISTO pravilo kao SURVEY/IDEA (grupa "resurs bez URL-a"):
-- RESURS_ID obavezan i pozitivan, AKCIJA_URL zabranjen.
-- ----------------------------------------------------------------------------
ALTER TABLE PULS_OBAVESTENJA DROP CONSTRAINT CK_OBAV_AKCIJA_TIP;
ALTER TABLE PULS_OBAVESTENJA ADD CONSTRAINT CK_OBAV_AKCIJA_TIP
    CHECK (AKCIJA_TIP IN ('NONE', 'SURVEY', 'IDEA', 'URL', 'IDEA_CYCLE'));

ALTER TABLE PULS_OBAVESTENJA DROP CONSTRAINT CK_OBAV_AKCIJA_PODACI;
ALTER TABLE PULS_OBAVESTENJA ADD CONSTRAINT CK_OBAV_AKCIJA_PODACI CHECK (
    (AKCIJA_TIP = 'NONE' AND RESURS_ID IS NULL AND AKCIJA_URL IS NULL) OR
    (AKCIJA_TIP IN ('SURVEY', 'IDEA', 'IDEA_CYCLE') AND RESURS_ID IS NOT NULL AND AKCIJA_URL IS NULL) OR
    (AKCIJA_TIP = 'URL' AND AKCIJA_URL IS NOT NULL AND RESURS_ID IS NULL));

COMMIT;
