-- ============================================================================
-- PULS - Modul ONBOARDING ANKETE (automatska dodela na 7/30/60/90 dana od
-- prvog zaposlenja) - infrastruktura (DDL). Sadrzaj cetiri ankete (Excel seed)
-- NIJE deo ove skripte - radi se posebno, kasnije.
--
-- SHEMA: PORTAL           TABLESPACE: GOMEX           ORACLE: 19c
--
-- !!! VAZNO !!!
-- Ova skripta se NE izvrsava automatski iz aplikacije. Mora se RUCNO pregledati
-- i pokrenuti (SQL Developer / SQL*Plus) tek nakon nezavisnog pregleda, POSLE
-- sql/001..005. Bez testnih INSERT-a/MERGE seed-a/DROP TABLE/DELETE/TRUNCATE.
--
-- Charset (isto pravilo kao ostali moduli):
--   NLS_CHARACTERSET       = EE8ISO8859P2  (NE cuva cirilicu/emoji u VARCHAR2!)
--   NLS_NCHAR_CHARACTERSET = AL16UTF16
--
-- DEO 5 (CREATE OR REPLACE VIEW/PROCEDURE) - originalne definicije procitane
-- READ-ONLY iz baze (DBMS_METADATA.GET_DDL, PORTAL sema, oba objekta VALID) i
-- sacuvane bez izmena u sql/006_before_onboarding_hr_objects.sql kao rollback
-- referenca. Deo 5 ove skripte sadrzi ISTI tekst aditivno dopunjen kolonom
-- DATUM_ZAPOSLENJA (LEFT JOIN na agregat HR.UGOVOR_RADNO_MESTO; NULL iz izvora
-- nikada ne brise postojecu vrednost pri sinhronizaciji).
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1) PULS_KORISNICI - dodaj DATUM_ZAPOSLENJA (prvo zaposlenje ikada).
--    Nullable jer postojeci korisnici nemaju ovu vrednost dok se ne izracuna
--    (backfill nije deo ove skripte - radi se posebno, van DDL-a).
-- ----------------------------------------------------------------------------
ALTER TABLE PULS_KORISNICI ADD DATUM_ZAPOSLENJA DATE;


-- ----------------------------------------------------------------------------
-- 2) PULS_ANKETA_AUTOMATIKA - pravilo automatske dodele jedne ankete na
--    milestone (7/30/60/90 dana od DATUM_ZAPOSLENJA). Jedna anketa = najvise
--    jedno pravilo (UNIQUE ANKETA_ID). AKTIVNA je istorizovana (moze postojati
--    vise neaktivnih redova za isti milestone - zato je zastita "najvise jedno
--    AKTIVNA='D' po milestone-u" function-based unique indeks, ne obican UNIQUE
--    constraint na (DANI_OD_ZAPOSLENJA)).
-- ----------------------------------------------------------------------------
CREATE TABLE PULS_ANKETA_AUTOMATIKA (
    ID                    NUMBER(19,0)  GENERATED BY DEFAULT AS IDENTITY,
    ANKETA_ID             NUMBER(19,0)  NOT NULL,
    DANI_OD_ZAPOSLENJA    NUMBER(3,0)   NOT NULL,
    ROK_DANA              NUMBER(3,0)   DEFAULT 7 NOT NULL,
    DATUM_PRIMENE_OD      DATE          NOT NULL,
    AKTIVNA               CHAR(1)       DEFAULT 'N' NOT NULL,
    DATUM_KREIRANJA       TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    DATUM_IZMENE          TIMESTAMP(6),
    CONSTRAINT PK_ANKETA_AUTOMATIKA PRIMARY KEY (ID),
    CONSTRAINT UX_ANKETA_AUTOMATIKA_ANKETA UNIQUE (ANKETA_ID),
    CONSTRAINT FK_ANKETA_AUTOMATIKA_ANKETA
        FOREIGN KEY (ANKETA_ID) REFERENCES PULS_ANKETE (ID),
    CONSTRAINT CK_ANKETA_AUTOMATIKA_DANI
        CHECK (DANI_OD_ZAPOSLENJA IN (7, 30, 60, 90)),
    CONSTRAINT CK_ANKETA_AUTOMATIKA_ROK
        CHECK (ROK_DANA BETWEEN 1 AND 365),
    CONSTRAINT CK_ANKETA_AUTOMATIKA_AKTIVNA
        CHECK (AKTIVNA IN ('D', 'N'))
);

-- Worker: pronalazenje aktivnih pravila (najcesci upit u discovery/dodeli).
CREATE INDEX IX_ANKETA_AUTOMATIKA_AKTIVNA ON PULS_ANKETA_AUTOMATIKA (AKTIVNA, DANI_OD_ZAPOSLENJA);

-- Najvise JEDNO AKTIVNA='D' pravilo po milestone-u; istorijska neaktivna pravila
-- (AKTIVNA='N') se ne ogranicavaju ovim indeksom jer NULL vrednosti izraz
-- izbacuje iz indeksa (funkcionalni indeks nad izrazom koji je NULL kada
-- AKTIVNA='N', pa se takvi redovi ne uzimaju u obzir za uniqueness).
CREATE UNIQUE INDEX UX_ANKETA_AUTOMATIKA_AKTIVNA_MILESTONE
    ON PULS_ANKETA_AUTOMATIKA (
        CASE WHEN AKTIVNA = 'D' THEN DANI_OD_ZAPOSLENJA ELSE NULL END
    );


-- ----------------------------------------------------------------------------
-- 3) PULS_ANKETA_UCESCA - dopuna za automatsku (onboarding) dodelu. Kod obicnog
--    ucesca (rucno dodeljena anketa) AUTOMATIKA_ID i pratece kolone ostaju NULL
--    (postojeci redovi ostaju validni bez izmene podataka). Kod automatskog
--    ucesca su sve popunjene, sto CHECK eksplicitno zahteva.
--    Postojeca UNIQUE zastita (ANKETA_ID, KORISNIK_ID) se ne dira.
-- ----------------------------------------------------------------------------
ALTER TABLE PULS_ANKETA_UCESCA ADD AUTOMATIKA_ID NUMBER(19,0);
ALTER TABLE PULS_ANKETA_UCESCA ADD DATUM_DOSTUPNOSTI TIMESTAMP(6);
ALTER TABLE PULS_ANKETA_UCESCA ADD DATUM_ISTEKA TIMESTAMP(6);
ALTER TABLE PULS_ANKETA_UCESCA ADD DATUM_ZAPOSLENJA_SNAPSHOT DATE;

ALTER TABLE PULS_ANKETA_UCESCA ADD CONSTRAINT FK_ANKETA_UCESCA_AUTOMATIKA
    FOREIGN KEY (AUTOMATIKA_ID) REFERENCES PULS_ANKETA_AUTOMATIKA (ID);

-- Sva cetiri automatska polja zajedno NULL (obicno ucesce) ili zajedno popunjena
-- (automatsko ucesce), i tada DATUM_ISTEKA mora biti STROGO posle DATUM_DOSTUPNOSTI
-- (interval [dostupno, istice) - sedam kalendarskih dana).
ALTER TABLE PULS_ANKETA_UCESCA ADD CONSTRAINT CK_ANKETA_UCESCA_AUTOMATIKA CHECK (
    (AUTOMATIKA_ID IS NULL AND DATUM_DOSTUPNOSTI IS NULL
        AND DATUM_ISTEKA IS NULL AND DATUM_ZAPOSLENJA_SNAPSHOT IS NULL)
    OR
    (AUTOMATIKA_ID IS NOT NULL AND DATUM_DOSTUPNOSTI IS NOT NULL
        AND DATUM_ISTEKA IS NOT NULL AND DATUM_ZAPOSLENJA_SNAPSHOT IS NOT NULL
        AND DATUM_ISTEKA > DATUM_DOSTUPNOSTI)
);

-- FK indeks: worker/upiti po pravilu automatike (AUTOMATIKA_ID) - isti obrazac
-- kao ostali IX_ indeksi u ovoj skripti (indeks za FK koji Oracle ne pravi sam).
CREATE INDEX IX_UCESCA_AUTOMATIKA
    ON PULS_ANKETA_UCESCA (AUTOMATIKA_ID);


-- ----------------------------------------------------------------------------
-- 4) PULS_SISTEMSKI_DOGADJAJI - kontrolisano prosirenje CK_SIST_DOG_TIP novim
--    tipom ONBOARDING_SURVEY_AVAILABLE (RESURS_ID = PULS_ANKETA_UCESCA.ID - ne
--    ANKETA_ID, jer je dodela per-korisnik). Postojeci tipovi se NE diraju -
--    skup dozvoljenih vrednosti se samo PROSIRUJE (isti obrazac kao u
--    sql/005_system_notifications_module.sql za CK_OBAV_AKCIJA_TIP).
-- ----------------------------------------------------------------------------
ALTER TABLE PULS_SISTEMSKI_DOGADJAJI DROP CONSTRAINT CK_SIST_DOG_TIP;
ALTER TABLE PULS_SISTEMSKI_DOGADJAJI ADD CONSTRAINT CK_SIST_DOG_TIP CHECK (TIP_DOGADJAJA IN (
    'SURVEY_ACTIVATED', 'SURVEY_EXPIRING',
    'IDEA_CYCLE_ACTIVATED', 'IDEA_CYCLE_EXPIRING',
    'IDEA_TOP_10', 'IDEA_NAGRADJENA',
    'APP_VERSION_CHANGED',
    'ONBOARDING_SURVEY_AVAILABLE'));


-- ----------------------------------------------------------------------------
-- 5) CREATE OR REPLACE PULS_V_AKTIVNI_ZAPOSLENI / PULS_SINHRONIZUJ_KORISNIKE
--
-- Aditivna izmena originalnih definicija (vidi sql/006_before_onboarding_hr_objects.sql
-- za tacan originalni tekst). Sva postojeca poslovna logika (telefon/statusi/
-- uloge/rasporedi/koraci 1-13 procedure) ostaje NETAKNUTA - dodaje se samo
-- kolona DATUM_ZAPOSLENJA.
-- ----------------------------------------------------------------------------

-- 5a) VIEW: dodata poslednja kolona DATUM_ZAPOSLENJA preko LEFT JOIN agregata
--     nad HR.UGOVOR_RADNO_MESTO (spoj po normalizovanom platnom broju
--     TRIM(CAST(... AS VARCHAR2(30))), isti obrazac kao ostatak view-a).
--     LEFT JOIN garantuje da zaposleni ne nestaje iz view-a ako datum nije
--     nadjen (DATUM_ZAPOSLENJA je tada NULL). Agregat iskljucuje buduce
--     datume (TRUNC(DATUMOD) <= TRUNC(SYSDATE)) i uzima MIN(TRUNC(DATUMOD))
--     kao datum prvog zaposlenja.
CREATE OR REPLACE FORCE EDITIONABLE VIEW "PORTAL"."PULS_V_AKTIVNI_ZAPOSLENI" ("PLATNI_BROJ", "IME", "PREZIME", "BROJ_TELEFONA", "ORGJED_SIFRA", "RADNO_MESTO_SIFRA", "DATUM_OD", "DATUM_DO", "DATUM_ZAPOSLENJA") AS
SELECT
    PLATNI_BROJ,
    IME,
    PREZIME,
    BROJ_TELEFONA,
    ORGJED_SIFRA,
    RADNO_MESTO_SIFRA,
    DATUM_OD,
    DATUM_DO,
    DATUM_ZAPOSLENJA
FROM (
    SELECT
        TRIM(CAST(k.PLATNIBROJ AS VARCHAR2(30))) AS PLATNI_BROJ,
        TRIM(k.IME) AS IME,
        TRIM(k.PREZIME) AS PREZIME,
        TRIM(k.TELEFON) AS BROJ_TELEFONA,
        CASE
            WHEN z.ORGJED IS NULL THEN NULL
            ELSE TRIM(CAST(z.ORGJED AS VARCHAR2(50)))
        END AS ORGJED_SIFRA,
        CASE
            WHEN z.RADNOMESTO IS NULL THEN NULL
            ELSE TRIM(CAST(z.RADNOMESTO AS VARCHAR2(50)))
        END AS RADNO_MESTO_SIFRA,
        z.DATUMOD AS DATUM_OD,
        z.DATUMDO AS DATUM_DO,
        -- NOVO: prvi datum zaposlenja iz HR.UGOVOR_RADNO_MESTO (NULL ako nije nadjen).
        HR_ZAP.DATUM_ZAPOSLENJA AS DATUM_ZAPOSLENJA,
        ROW_NUMBER() OVER (
            PARTITION BY k.PLATNIBROJ
            ORDER BY
                z.DATUMOD DESC,
                NVL(z.DATUMDO, DATE '9999-12-31') DESC,
                z.ORGJED NULLS LAST,
                z.RADNOMESTO NULLS LAST
        ) AS RN
    FROM HR.KADROVI k
    INNER JOIN HR.ZAPOSLENJA z
        ON z.PLATNIBROJ = k.PLATNIBROJ
    -- NOVO: LEFT JOIN agregat za DATUM_ZAPOSLENJA - ne uklanja redove kada nema podatka.
    LEFT JOIN (
        SELECT
            TRIM(CAST(PLATNIBROJ AS VARCHAR2(30))) AS PLATNI_BROJ,
            MIN(TRUNC(DATUMOD)) AS DATUM_ZAPOSLENJA
        FROM HR.UGOVOR_RADNO_MESTO
        WHERE PLATNIBROJ IS NOT NULL
          AND DATUMOD IS NOT NULL
          AND TRUNC(DATUMOD) <= TRUNC(SYSDATE)
        GROUP BY TRIM(CAST(PLATNIBROJ AS VARCHAR2(30)))
    ) HR_ZAP ON HR_ZAP.PLATNI_BROJ = TRIM(CAST(k.PLATNIBROJ AS VARCHAR2(30)))
    WHERE k.PLATNIBROJ IS NOT NULL
      AND z.DATUMOD IS NOT NULL
      AND TRUNC(z.DATUMOD) <= TRUNC(SYSDATE)
      AND (
            z.DATUMDO IS NULL
            OR TRUNC(z.DATUMDO) >= TRUNC(SYSDATE)
          )
)
WHERE RN = 1
/


-- 5b) PROCEDURE: ista logika kao original (koraci 1-13 netaknuti), aditivno
--     dopunjena samo u KORAKU 4 (INSERT novih korisnika) i KORAKU 5 (MERGE
--     azuriranje postojecih korisnika) da prenesu/sinhronizuju DATUM_ZAPOSLENJA.
CREATE OR REPLACE EDITIONABLE PROCEDURE "PORTAL"."PULS_SINHRONIZUJ_KORISNIKE"
IS

    /* =========================================================
       PROMENLJIVE ZA PRACENJE SINHRONIZACIJE
       ========================================================= */

    -- ID zapisa iz PULS_SINHRONIZACIJE za trenutno izvrsavanje
    v_sinhronizacija_id     PULS_SINHRONIZACIJE.ID%TYPE;

    -- ID osnovne uloge ZAPOSLENI
    v_uloga_zaposleni_id    PULS_ULOGE.ID%TYPE;


    /* =========================================================
       BROJACI REZULTATA SINHRONIZACIJE
       ========================================================= */

    v_broj_dodatih          NUMBER := 0;
    v_broj_izmenjenih       NUMBER := 0;
    v_broj_deaktiviranih    NUMBER := 0;
    v_broj_reaktiviranih    NUMBER := 0;
    v_broj_gresaka          NUMBER := 0;


    /* =========================================================
       PROMENLJIVA ZA CUVANJE TEKSTA GRESKE
       ========================================================= */

    v_greska                VARCHAR2(4000);

BEGIN

    /* =========================================================
       KORAK 1
       OTVARANJE NOVOG ZAPISA SINHRONIZACIJE
       ========================================================= */

    INSERT INTO PULS_SINHRONIZACIJE (
        TIP_SINHRONIZACIJE,
        STATUS,
        DATUM_POCETKA
    )
    VALUES (
        'KORISNICI',
        'U_TOKU',
        SYSTIMESTAMP
    )
    RETURNING ID
    INTO v_sinhronizacija_id;


    /* COMMIT je ovde nameran - zapis o pocetku ostaje sacuvan i ako procedura
       kasnije zavrsi greskom. */
    COMMIT;



    /* =========================================================
       KORAK 2
       PRONALAZENJE OSNOVNE ULOGE ZAPOSLENI
       ========================================================= */

    BEGIN

        SELECT ID
          INTO v_uloga_zaposleni_id
          FROM PULS_ULOGE
         WHERE SIFRA = 'ZAPOSLENI'
           AND AKTIVNA = 'D';

    EXCEPTION

        WHEN NO_DATA_FOUND THEN

            RAISE_APPLICATION_ERROR(
                -20001,
                'Nije pronadjena aktivna PULS uloga ZAPOSLENI.'
            );

        WHEN TOO_MANY_ROWS THEN

            RAISE_APPLICATION_ERROR(
                -20002,
                'Postoji vise aktivnih PULS uloga sa sifrom ZAPOSLENI.'
            );

    END;



    /* =========================================================
       KORAK 3
       PROVERA NEKOMPLETNIH HR PODATAKA
       ========================================================= */

    SELECT COUNT(*)
      INTO v_broj_gresaka
      FROM PULS_V_AKTIVNI_ZAPOSLENI
     WHERE IME IS NULL
        OR PREZIME IS NULL;



    /* =========================================================
       KORAK 4
       KREIRANJE NOVIH PULS KORISNIKA

       IZMENA (aditivno): dodata kolona DATUM_ZAPOSLENJA u INSERT listu i
       odgovarajuca vrednost s.DATUM_ZAPOSLENJA iz view-a (novi korisnik odmah
       dobija datum prvog zaposlenja ako je poznat u HR-u).
       ========================================================= */

    INSERT INTO PULS_KORISNICI (
        PLATNI_BROJ,
        IME,
        PREZIME,
        BROJ_TELEFONA,
        LOZINKA_HASH,
        STATUS_ZAPOSLENJA,
        STATUS_NALOGA,
        OBAVEZNA_PROMENA_LOZINKE,
        TELEFON_POTVRDJEN,
        BROJ_NEUSPESNIH_PRIJAVA,
        ZAKLJUCAN,
        DATUM_SINHRONIZACIJE,
        DATUM_ZAPOSLENJA
    )
    SELECT
        s.PLATNI_BROJ,
        s.IME,
        s.PREZIME,
        s.BROJ_TELEFONA,

        -- Lozinku nece generisati Oracle procedura.
        -- To ce naknadno uraditi backend.
        NULL,

        -- Korisnik postoji u aktivnim HR zaposlenjima.
        'AKTIVAN',

        -- Novi nalog je po default-u omogucen.
        'OMOGUCEN',

        -- Pri prvom login-u mora promeniti pocetnu lozinku.
        'D',

        -- Telefon jos nije potvrdjen kroz aplikaciju.
        'N',

        -- Novi korisnik nema neuspesnih login pokusaja.
        0,

        -- Novi korisnik nije zakljucan.
        'N',

        SYSTIMESTAMP,

        -- NOVO: prvi datum zaposlenja iz HR-a (moze biti NULL).
        s.DATUM_ZAPOSLENJA

    FROM PULS_V_AKTIVNI_ZAPOSLENI s

    WHERE s.IME IS NOT NULL
      AND s.PREZIME IS NOT NULL

      AND NOT EXISTS (
            SELECT 1
              FROM PULS_KORISNICI k
             WHERE k.PLATNI_BROJ = s.PLATNI_BROJ
      );


    v_broj_dodatih := SQL%ROWCOUNT;



    /* =========================================================
       KORAK 5
       AZURIRANJE POSTOJECIH KORISNIKA

       IZMENA (aditivno):
       - izvorni SELECT (USING) sada eksplicitno ukljucuje DATUM_ZAPOSLENJA.
       - UPDATE SET dodaje k.DATUM_ZAPOSLENJA, ali SAMO kada je izvorni datum
         IS NOT NULL (CASE WHEN ... ELSE k.DATUM_ZAPOSLENJA) - NULL iz izvora
         NIKADA ne brise postojecu vrednost.
       - WHERE klauzula MATCHED grane dopunjena OR uslovom za slucaj kada se
         JEDINO DATUM_ZAPOSLENJA promenio (izvor ima vrednost razlicitu od
         trenutne, poredjenje datuma bez implicitne konverzije stringa).
       ========================================================= */

    MERGE INTO PULS_KORISNICI k

    USING (
        SELECT
            PLATNI_BROJ,
            IME,
            PREZIME,
            BROJ_TELEFONA,
            DATUM_ZAPOSLENJA
        FROM PULS_V_AKTIVNI_ZAPOSLENI
        WHERE IME IS NOT NULL
          AND PREZIME IS NOT NULL
    ) s

    ON (
        k.PLATNI_BROJ = s.PLATNI_BROJ
    )

    WHEN MATCHED THEN

        UPDATE SET

            /* Ime uvek prati HR podatke. */
            k.IME = s.IME,

            /* Prezime uvek prati HR podatke. */
            k.PREZIME = s.PREZIME,

            /* Telefon menjamo samo ako u PULS-u jos ne postoji. */
            k.BROJ_TELEFONA =
                CASE
                    WHEN k.BROJ_TELEFONA IS NULL
                    THEN s.BROJ_TELEFONA
                    ELSE k.BROJ_TELEFONA
                END,

            /* NOVO: DATUM_ZAPOSLENJA sinhronizujemo samo kada izvor ima
               vrednost - NULL iz izvora nikad ne brise postojeci datum. */
            k.DATUM_ZAPOSLENJA =
                CASE
                    WHEN s.DATUM_ZAPOSLENJA IS NOT NULL
                    THEN s.DATUM_ZAPOSLENJA
                    ELSE k.DATUM_ZAPOSLENJA
                END

        WHERE
               NVL(k.IME, '[NULL]')
                    <> NVL(s.IME, '[NULL]')

            OR NVL(k.PREZIME, '[NULL]')
                    <> NVL(s.PREZIME, '[NULL]')

            OR (
                k.BROJ_TELEFONA IS NULL
                AND s.BROJ_TELEFONA IS NOT NULL
            )

            /* NOVO: azuriraj i kada se jedino DATUM_ZAPOSLENJA promenio
               (eksplicitno poredjenje DATE vrednosti, bez konverzije stringa). */
            OR (
                s.DATUM_ZAPOSLENJA IS NOT NULL
                AND (
                    k.DATUM_ZAPOSLENJA IS NULL
                    OR TRUNC(k.DATUM_ZAPOSLENJA) <> TRUNC(s.DATUM_ZAPOSLENJA)
                )
            );


    v_broj_izmenjenih := SQL%ROWCOUNT;



    /* =========================================================
       KORAK 6
       REAKTIVACIJA KORISNIKA
       ========================================================= */

    UPDATE PULS_KORISNICI k

       SET k.STATUS_ZAPOSLENJA = 'AKTIVAN',
           k.DATUM_SINHRONIZACIJE = SYSTIMESTAMP

     WHERE k.STATUS_ZAPOSLENJA = 'NEAKTIVAN'

       AND EXISTS (
            SELECT 1
              FROM PULS_V_AKTIVNI_ZAPOSLENI s
             WHERE s.PLATNI_BROJ = k.PLATNI_BROJ
       );


    v_broj_reaktiviranih := SQL%ROWCOUNT;



    /* =========================================================
       KORAK 7
       DEAKTIVACIJA KORISNIKA
       ========================================================= */

    UPDATE PULS_KORISNICI k

       SET k.STATUS_ZAPOSLENJA = 'NEAKTIVAN',
           k.DATUM_SINHRONIZACIJE = SYSTIMESTAMP

     WHERE k.STATUS_ZAPOSLENJA = 'AKTIVAN'

       AND NOT EXISTS (
            SELECT 1
              FROM PULS_V_AKTIVNI_ZAPOSLENI s
             WHERE s.PLATNI_BROJ = k.PLATNI_BROJ
       );


    v_broj_deaktiviranih := SQL%ROWCOUNT;



    /* =========================================================
       KORAK 8
       OSVEZAVANJE DATUMA SINHRONIZACIJE
       ========================================================= */

    UPDATE PULS_KORISNICI k

       SET k.DATUM_SINHRONIZACIJE = SYSTIMESTAMP

     WHERE EXISTS (
            SELECT 1
              FROM PULS_V_AKTIVNI_ZAPOSLENI s
             WHERE s.PLATNI_BROJ = k.PLATNI_BROJ
       );



    /* =========================================================
       KORAK 9
       DODELA OSNOVNE ULOGE ZAPOSLENI
       ========================================================= */

    INSERT INTO PULS_KORISNIK_ULOGE (
        KORISNIK_ID,
        ULOGA_ID,
        DODELIO_KORISNIK_ID,
        DATUM_DODELE
    )
    SELECT
        k.ID,
        v_uloga_zaposleni_id,

        NULL,

        SYSTIMESTAMP

    FROM PULS_KORISNICI k

    WHERE EXISTS (
            SELECT 1
              FROM PULS_V_AKTIVNI_ZAPOSLENI s
             WHERE s.PLATNI_BROJ = k.PLATNI_BROJ
    )

      AND NOT EXISTS (
            SELECT 1
              FROM PULS_KORISNIK_ULOGE ku
             WHERE ku.KORISNIK_ID = k.ID
               AND ku.ULOGA_ID = v_uloga_zaposleni_id
    );



    /* =========================================================
       KORAK 10
       DEAKTIVACIJA RASPOREDA NEAKTIVNIH KORISNIKA
       ========================================================= */

    UPDATE PULS_KORISNIK_RASPOREDI kr

       SET kr.AKTIVAN = 'N',
           kr.PRIMARNI = 'N',
           kr.DATUM_SINHRONIZACIJE = SYSTIMESTAMP

     WHERE kr.AKTIVAN = 'D'

       AND EXISTS (
            SELECT 1
              FROM PULS_KORISNICI k
             WHERE k.ID = kr.KORISNIK_ID
               AND k.STATUS_ZAPOSLENJA = 'NEAKTIVAN'
       );



    /* =========================================================
       KORAK 11
       DEAKTIVACIJA STAROG RASPOREDA
       ========================================================= */

    UPDATE PULS_KORISNIK_RASPOREDI kr

       SET kr.AKTIVAN = 'N',
           kr.PRIMARNI = 'N',
           kr.DATUM_SINHRONIZACIJE = SYSTIMESTAMP

     WHERE kr.AKTIVAN = 'D'

       AND EXISTS (
            SELECT 1
              FROM PULS_KORISNICI k

              JOIN PULS_V_AKTIVNI_ZAPOSLENI s
                ON s.PLATNI_BROJ = k.PLATNI_BROJ

             WHERE k.ID = kr.KORISNIK_ID
       )

       AND NOT EXISTS (
            SELECT 1
              FROM PULS_KORISNICI k

              JOIN PULS_V_AKTIVNI_ZAPOSLENI s
                ON s.PLATNI_BROJ = k.PLATNI_BROJ

             WHERE k.ID = kr.KORISNIK_ID

               AND s.ORGJED_SIFRA IS NOT NULL

               AND kr.ORGJED_SIFRA = s.ORGJED_SIFRA

               AND NVL(
                       kr.RADNO_MESTO_SIFRA,
                       '[NULL]'
                   )
                   =
                   NVL(
                       s.RADNO_MESTO_SIFRA,
                       '[NULL]'
                   )
       );



    /* =========================================================
       KORAK 12
       SINHRONIZACIJA TRENUTNOG RASPOREDA
       ========================================================= */

    MERGE INTO PULS_KORISNIK_RASPOREDI kr

    USING (
        SELECT
            k.ID AS KORISNIK_ID,
            s.ORGJED_SIFRA,
            s.RADNO_MESTO_SIFRA,
            s.DATUM_OD,
            s.DATUM_DO

        FROM PULS_KORISNICI k

        INNER JOIN PULS_V_AKTIVNI_ZAPOSLENI s
            ON s.PLATNI_BROJ = k.PLATNI_BROJ

        WHERE s.ORGJED_SIFRA IS NOT NULL
          AND k.STATUS_ZAPOSLENJA = 'AKTIVAN'

    ) s

    ON (
           kr.KORISNIK_ID = s.KORISNIK_ID

       AND kr.ORGJED_SIFRA = s.ORGJED_SIFRA

       AND NVL(
               kr.RADNO_MESTO_SIFRA,
               '[NULL]'
           )
           =
           NVL(
               s.RADNO_MESTO_SIFRA,
               '[NULL]'
           )

       AND kr.AKTIVAN = 'D'
    )

    WHEN MATCHED THEN

        UPDATE SET

            kr.PRIMARNI = 'D',

            kr.DATUM_OD = s.DATUM_OD,

            kr.DATUM_DO = s.DATUM_DO,

            kr.DATUM_SINHRONIZACIJE = SYSTIMESTAMP

    WHEN NOT MATCHED THEN

        INSERT (
            KORISNIK_ID,
            ORGJED_SIFRA,
            RADNO_MESTO_SIFRA,
            PRIMARNI,
            AKTIVAN,
            DATUM_OD,
            DATUM_DO,
            DATUM_SINHRONIZACIJE
        )

        VALUES (
            s.KORISNIK_ID,
            s.ORGJED_SIFRA,
            s.RADNO_MESTO_SIFRA,

            'D',

            'D',

            s.DATUM_OD,
            s.DATUM_DO,

            SYSTIMESTAMP
        );



    /* =========================================================
       KORAK 13
       ZATVARANJE SINHRONIZACIJE
       ========================================================= */

    UPDATE PULS_SINHRONIZACIJE

       SET STATUS =
            CASE
                WHEN v_broj_gresaka > 0
                THEN 'DELIMICNA'
                ELSE 'USPESNA'
            END,

           DATUM_ZAVRSETKA = SYSTIMESTAMP,

           BROJ_DODATIH = v_broj_dodatih,

           BROJ_IZMENJENIH = v_broj_izmenjenih,

           BROJ_DEAKTIVIRANIH = v_broj_deaktiviranih,

           BROJ_REAKTIVIRANIH = v_broj_reaktiviranih,

           BROJ_GRESAKA = v_broj_gresaka,

           OPIS_GRESKE =
            CASE
                WHEN v_broj_gresaka > 0
                THEN
                    'Postoje aktivni HR zapisi bez IMENA ili PREZIMENA. '
                    || 'Takvi novi korisnici nisu kreirani.'
                ELSE
                    NULL
            END

     WHERE ID = v_sinhronizacija_id;


    COMMIT;


EXCEPTION

    WHEN OTHERS THEN

        ROLLBACK;

        v_greska :=
              'SQLCODE='
           || SQLCODE
           || '; SQLERRM='
           || SUBSTR(
                SQLERRM,
                1,
                1500
              )
           || '; BACKTRACE='
           || SUBSTR(
                DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,
                1,
                2000
              );

        UPDATE PULS_SINHRONIZACIJE

           SET STATUS = 'GRESKA',

               DATUM_ZAVRSETKA = SYSTIMESTAMP,

               BROJ_DODATIH = 0,

               BROJ_IZMENJENIH = 0,

               BROJ_DEAKTIVIRANIH = 0,

               BROJ_REAKTIVIRANIH = 0,

               BROJ_GRESAKA = 1,

               OPIS_GRESKE = v_greska

         WHERE ID = v_sinhronizacija_id;

        COMMIT;

        RAISE;

END;
/


COMMIT;
